### ISSUE TITLE
Inputs and dropdown elements partially follow builtin browser theme, causing confusion

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#806]
### Expected Behavior

Compare with the screenshot in Actual Behavior.

* Text and number inputs ("sprite", "x", "y", "direction", "costume", brush size) are all filled black, with the text a grayish text color that does not contrast well.

* Dropdown inputs ("rotation", language) are completely unstyled and don't fit in with the UI.

* Scroll bars should be themed the same way they are in scratch-blocks.

### Actual Behavior

Sprite corral tools:

![Screenshot of sprite corral tools](https://user-images.githubusercontent.com/9948030/31948435-5693ae4a-b8ad-11e7-8b16-831213dad13c.png)

Paint tools:

![Screenshot of paint tools](https://user-images.githubusercontent.com/9948030/31948450-60787fda-b8ad-11e7-9a92-bf066c793e83.png)

Language dropdown:

![Screenshot of language dropdown](https://user-images.githubusercontent.com/9948030/31948470-68877604-b8ad-11e7-88e3-c68c4ee40d08.png)

Scrollbar compraison (left is scratch-blocks, right is scratch-gui elements (sprite corral)):

![Screenshot of scrollbars](https://user-images.githubusercontent.com/9948030/31949149-f8bb4880-b8ae-11e7-9ffb-cc612ceb93ce.png)

Note that elements in scratch-blocks look normal -- block dropdowns are the right color, the zoom buttons look normal, etc. This is only related to browser-default colors for elements like `<input>`.

### Steps to Reproduce

Open scratch-gui and view input elements such as that one.

### Operating System and Browser

Debian Testing. Firefox 57.0 (developer edition), though this is also a problem in previous versions. GTK+ theme Ark-Dark, as set with GNOME Tweak Tool.

---

Honestly it looks like the solution could be as simple as setting a background color on these elements. Here's what the sprite corral tools looked like when I set `background: #DDD` on the `<input>` elements:

![Screenshot of corral tools with edited CSS](https://user-images.githubusercontent.com/9948030/31949041-b70f37ac-b8ae-11e7-9fe5-cefa60f9e394.png)

The dropdown issue might be separate (it looks like they aren't being styled at all yet).

**Comment by kyleplo** [comment]
Fixed.

**Comment by towerofnix** [comment]
@kyleplo Yeah, almost -- the scrollbar still isn't styled, but I'll leave that as a separate to-do, especially since this mostly relates to the sprite section, which is otherwise looking correct (and no scrollbars anywhere outside of scratch-blocks are styled yet).
